spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/test?useServerPrepStmts=false&allowMultiQueries=true
    username: holeman79
    password: 1234

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
  mybatis:
    mapperlocations: classpath:/seoulapp/test/**/*Dao.xml
    configuration:
      lazyLoadingEnabled=true
      aggressiveLazyLoading=false
      mapUnderscoreToCamelCase=true
  
        