spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://222.99.195.194:3306/seoulapp?useServerPrepStmts=false&allowMultiQueries=true
    username: holeman79
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
  
        
mybatis:
  mapper-locations: classpath:seoulapp/test/**/*Dao.xml



  
  
        