spring:
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3306/seoulapp?useServerPrepStmts=false&allowMultiQueries=true
    username: holeman79
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        
mybatis:
  mapper-locations: classpath:seoulapp/test/**/*Dao.xml



  
  
        